languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Rocker Project"
theme = "hugo-material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Carl Boettiger"
  bio = ""
  job = "Assistant Professor"
  location = "UC Berkeley"
  gravatarEmail = "cboettig@gmail.com"
  twitter = "cboettig"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "images"
  name = "Images"
  pre = "<i class='material-icons'>computer</i>"
  #pre = "<i class='now-ui-icons arrows-1_cloud-download-93'></i>"
  url = "/images"
[[menu.main]]
  weight = 2
  identifier = "use"
  name = "Use"
  pre = "<i class='material-icons'>settings</i>"
#  pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
  url = "/use"
[[menu.main]]
  parent = "use"
  weight = 1
  pre = "<i class=\"material-icons\">folder_shared</i>"
  name = "Shared volumes"
  url = "/use/shared_volumes"
[[menu.main]]
  parent = "use"
  weight = 2
  pre = " <i class=\"material-icons\">people</i>"
  name = "Managing users"
  url = "/use/managing_users"
[[menu.main]]
  parent = "use"
  weight = 3
  pre = " <i class=\"material-icons\">settings_input_component</i>"
  name = "Networking"
  url = "/use/networking"
[[menu.main]]
  parent = "use"
  weight = 4
  pre = " <i class=\"material-icons\">extension</i>"
  name = "Extending Images"
  url = "/use/extending"  
[[menu.main]]
  parent = "use"
  weight = 4
  pre = " <i class=\"material-icons\">build</i>"
  name = "Container management"
  url = "/use/managing_containers"  
[[menu.main]]
  parent = "use"
  weight = 4
  pre = " <i class=\"material-icons\">explore</i>"
  name = "Other topics"
  url = "/use/other_topics"  


[[menu.footer]]
  weight = 1
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i> "
  url = "https://github.com/rocker-org"
[[menu.footer]]
  weight = 2
  name = "Docker Hub"
  pre = "<i class=\"button-icon fa fa-2x fa-docker\"></i> "
  url = "https://hub.docker.com/u/rocker"
[[menu.footer]]
  weight = 3
  name = "Code of Conduct"
  pre = "<i class=\"button-icon fa fa-2x user-friends\"></i> "
  url = "/conduct"


[params]
  profile = "/img/rocker.png"
  dateFormat = "January 2, 2006"
  background = "/img/goldengate.jpg"
  icon = "img/rocker-bw.png"
  custom_css = ["https://fonts.googleapis.com/icon?family=Material+Icons",
                "https://cdn.jsdelivr.net/gh/gaborcsardi/r-font/rlogo.css",
                "https://cdn.jsdelivr.net/gh/wesbos/Font-Awesome-Docker-Icon/fontcustom/fontcustom.css"]
#  custom_js = ["js/custom.js"]
